baseURL = "https://www.togglee.com/"
title = "Togglee"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Get Started'
  homepage_intro = 'Togglee is a feature toggle library for multiple programming languages that does not require any server to update your toggles'
  homepage_image = ''

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Togglee is a feature toggle serverless library"
    meta_og_title = "Togglee"
    meta_og_type = "website"
    meta_og_url = "https://togglee.com"
    meta_og_image = ""
    meta_og_description = "Togglee is a feature toggle library for multiple programming languages that does not require any server to update your toggles"
    meta_twitter_card = "summary"
    meta_twitter_site = "@togglee"
    meta_twitter_creator = "@kanekotic"

  [params.logo]
      mobile = "/images/logo-1.png"
      standard  = "/images/logo-1.png"
